package at.qe.skeleton.model;
public enum SensorType {

    SOIL_HUMIDITY, //BODENFEUCHTIGKEIT
    TEMPERATURE, //TEMPERATUR
    AIR_HUMIDITY, //LUFTFEUCHTIGKEIT
    AIR_PRESSURE, //LUFTDRUCK
    AIR_QUALITY, //LUFTQUALITÄT
    LIGHT //LICHT

}
